/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "counter.v:1.1-14.10" *)
module counter(clk, rst, count);
  wire _00_;
  wire _01_;
  (* src = "counter.v:11.22-11.31|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _02_;
  (* src = "counter.v:11.22-11.31|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _03_;
  (* src = "counter.v:11.22-11.31|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _04_;
  (* src = "counter.v:11.22-11.31|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _05_;
  (* src = "counter.v:4.22-4.27" *)
  wire _06_;
  (* src = "counter.v:4.22-4.27" *)
  wire _07_;
  (* src = "counter.v:4.22-4.27" *)
  wire _08_;
  (* src = "counter.v:4.22-4.27" *)
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:11.22-11.31|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _20_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:11.22-11.31|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _21_;
  (* src = "counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "counter.v:4.22-4.27" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "counter.v:3.11-3.14" *)
  input rst;
  wire rst;
  assign _02_ = ~_06_;
  assign _10_ = ~_07_;
  assign _11_ = ~_08_;
  assign _12_ = ~(_02_ | _10_);
  assign _13_ = ~(_06_ & _07_);
  assign _14_ = ~(_06_ | _07_);
  assign _03_ = ~(_12_ | _14_);
  assign _15_ = ~(_11_ | _13_);
  assign _16_ = ~(_08_ | _12_);
  assign _04_ = ~(_15_ | _16_);
  assign _17_ = ~(_09_ | _15_);
  assign _18_ = ~(_09_ & _15_);
  assign _19_ = ~_18_;
  assign _05_ = ~(_17_ | _19_);
  (* src = "counter.v:7.5-12.8" *)
  always @(posedge clk, posedge rst)
    if (rst) count[0] <= 1'h0;
    else count[0] <= _20_[0];
  (* src = "counter.v:7.5-12.8" *)
  always @(posedge clk, posedge rst)
    if (rst) count[1] <= 1'h0;
    else count[1] <= _21_[1];
  (* src = "counter.v:7.5-12.8" *)
  always @(posedge clk, posedge rst)
    if (rst) count[2] <= 1'h0;
    else count[2] <= _21_[2];
  (* src = "counter.v:7.5-12.8" *)
  always @(posedge clk, posedge rst)
    if (rst) count[3] <= 1'h0;
    else count[3] <= _21_[3];
  assign _20_[3:1] = count[3:1];
  assign _21_[0] = _20_[0];
  assign _06_ = count[0];
  assign _20_[0] = _02_;
  assign _07_ = count[1];
  assign _21_[1] = _03_;
  assign _08_ = count[2];
  assign _21_[2] = _04_;
  assign _09_ = count[3];
  assign _21_[3] = _05_;
endmodule
