/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "counter.v:1.1-14.10" *)
module counter(clk, rst, count);
  wire _00_;
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:11.22-11.31|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:11.22-11.31|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _03_;
  (* src = "counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "counter.v:4.22-4.27" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "counter.v:3.11-3.14" *)
  input rst;
  wire rst;
  assign _02_[0] = ~count[0];
  assign _03_[1] = count[1] ^ count[0];
  assign _00_ = ~(count[1] & count[0]);
  assign _03_[2] = ~(_00_ ^ count[2]);
  assign _01_ = count[2] & ~(_00_);
  assign _03_[3] = _01_ ^ count[3];
  (* src = "counter.v:7.5-12.8" *)
  always @(posedge clk, posedge rst)
    if (rst) count[0] <= 1'h0;
    else count[0] <= _02_[0];
  (* src = "counter.v:7.5-12.8" *)
  always @(posedge clk, posedge rst)
    if (rst) count[1] <= 1'h0;
    else count[1] <= _03_[1];
  (* src = "counter.v:7.5-12.8" *)
  always @(posedge clk, posedge rst)
    if (rst) count[2] <= 1'h0;
    else count[2] <= _03_[2];
  (* src = "counter.v:7.5-12.8" *)
  always @(posedge clk, posedge rst)
    if (rst) count[3] <= 1'h0;
    else count[3] <= _03_[3];
  assign _02_[3:1] = count[3:1];
  assign _03_[0] = _02_[0];
endmodule
