/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* cells_not_processed =  1  *)
(* src = "counter.v:1.1-14.10" *)
module counter(clk, rst, count);
  reg \$auto$verilog_backend.cc:2184:dump_module$3  = 0;
  (* src = "counter.v:7.5-12.8" *)
  reg [3:0] _0_;
  (* src = "counter.v:11.22-11.31" *)
  wire [31:0] _1_;
  (* src = "counter.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "counter.v:4.22-4.27" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "counter.v:3.11-3.14" *)
  input rst;
  wire rst;
  assign _1_ = count + (* src = "counter.v:11.22-11.31" *) 32'd1;
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$3 ) begin end
    _0_ = count;
    (* src = "counter.v:8.9-11.32" *)
    casez (rst)
      /* src = "counter.v:8.13-8.16" */
      1'h1:
          _0_ = 4'h0;
      /* src = "counter.v:10.9-10.13" */
      default:
          _0_ = _1_[3:0];
    endcase
  end
  always @(posedge clk) begin
      count <= _0_;
  end
  always @(posedge rst) begin
      count <= _0_;
  end
endmodule
